import Candidate from "../modals/Candidate/Candidate";
import CandidateReasons from "../modals/CandidateReasons/CandidateReasons";
import CandidateTags from "../modals/CandidateTags/CandidateTags";
import Client from "../modals/Client/Client";
import Degree from "../modals/DegreeProgram/Degree";
import Designation from "../modals/Designation/Designation";
import Education from "../modals/Eduction/Education";
import ReasonsForLeaving from "../modals/ReasonForLeaving/ReasonForLeaving";
import Region from "../modals/Region/Region";
import Tag from "../modals/Tag/Tag";
import Token from "../modals/Token/Token";
import User from "../modals/User/User";
import ClientTags from "../modals/ClientTags";
import SecurityQuestion from "../modals/SecurityQuestions/index";
import UserSecurityAnswer from "../modals/UserSecurityAnswer/index";
import ReasonAnswer from "../modals/ReasonAnswer/ReasonAnswer";
import ReasonSaveAnswer from "../modals/ReasonSaveAnswer/ReasonSaveAnswer";
async function syncdatabase() {
  // await ClientSecurity.sync();
  await User.sync({alter: true});
  await Token.sync();
  await Tag.sync();
  await ReasonsForLeaving.sync();
  await Designation.sync();
  await Region.sync();
  await Candidate.sync();
  await CandidateTags.sync();
  await CandidateReasons.sync();
  await Education.sync();
  await Client.sync({alter: true});
  await Degree.sync();
  await ClientTags.sync();
  await SecurityQuestion.sync();
  await UserSecurityAnswer.sync();
  await ReasonAnswer.sync();
  await ReasonSaveAnswer.sync();
}
export default syncdatabase;
